---
title: "Escaping the circles of installation hell"
author:
  - name: Raniere Silva
    orcid: 0000-0002-8381-3749
    email: Raniere.CostadaSilva@gesis.org
    affiliations:
      - name: GESIS Leibniz Institute for the Social Sciences
  - name: Jannetta Steyn
    affiliations:
      - name: Newcastle University
format:
  revealjs:
    min-scale: 1
    max-scale: 1
---

## Software Carpentry 1.0

::: {.notes}
This is how Software Carpentry started.
:::

> In response, John Reynders (then director of the Advanced Computing Laboratory at Los Alamos National Laboratory) invited the [Greg Wilson] and Brent Gorda (now at Intel) to teach a week-long course to LANL staff. This course ran for the first time in July 1998, and was repeated nine times over the next four years.

Wilson G. Software Carpentry: lessons learned [version 2; peer review: 3 approved]. F1000Research 2016, 3:62 ([https://doi.org/10.12688/f1000research.3-62.v2](https://doi.org/10.12688/f1000research.3-62.v2)) 

## In July of 1998 ...

::: {.notes}
This a summary of the software landscape when Software Carpentry started.
:::

:::: {.columns}

::: {.column width="50%"}
### Python

Version [1.5.1](https://github.com/python/cpython/releases/tag/v1.5.1) is the latest release.

Python Package Index (PyPI) has **not** been created, [PyPI was launched in 2003](https://en.wikipedia.org/wiki/Python_Package_Index).

Numeric (now called NumPy) was [announced in 1995](http://hugunin.net/papers/hugunin95numpy.html). matplotlib has **not** been created, [matplotlib first release was in 2003](https://matplotlib.org/stable/project/license.html#copyright-policy).

<!-- SciPy has not been created, [first release around 2001](https://arxiv.org/abs/1907.10121). -->
:::

::: {.column width="50%"}
### R

Version [0.62.2](https://cran.r-project.org/src/base/R-0/) is the latest release.

The Comprehensive R Archive Network [(CRAN) was launched the year before (1997)](https://en.wikipedia.org/wiki/R_(programming_language)).

ggplot (now called ggplot2) has **not** been created, [ggplot first release was in 2006](https://cran.r-project.org/src/contrib/Archive/ggplot/).
:::

::::

## Also in July of 1998 ...

Microsoft's [Windows 98 was released the month before (June 1998)](https://en.wikipedia.org/wiki/Windows_98).

Apple's [Mac OS 8 was released the year before (1997)](https://en.wikipedia.org/wiki/Classic_Mac_OS#Mac_OS_8).

[Concurrent Versions System](https://en.wikipedia.org/wiki/Concurrent_Versions_System) (CVS) was the most popular version control system.

[The first x86 virtualization product was under development](https://en.wikipedia.org/wiki/Timeline_of_virtualization_technologies#1990s) by VMware.

## Back to the Future, or 2012

::: {.notes}
This is when Raniere got involved with Software Carpentry.
:::

> Software Carpentry rebooted again in January 2012 with a grant from the Sloan Foundation to the Mozilla Foundation. This time, the model was two-day intensive workshops like those pioneered by The Hacker Within, a grassroots group of grad students helping grad students at the University of Wisconsin - Madison.

Wilson G. Software Carpentry: lessons learned [version 2; peer review: 3 approved]. F1000Research 2016, 3:62 ([https://doi.org/10.12688/f1000research.3-62.v2](https://doi.org/10.12688/f1000research.3-62.v2)) 

## In 2012 ...

::: {.notes}
This a summary of the software landscape when Software Carpentry rebooted as part of Mozilla Science Lab. This was soon after the first release of IPython Notebook and RStudio IDE.
:::

:::: {.columns}

::: {.column width="50%"}
### Python

Versions [2.7.3](https://github.com/python/cpython/releases/tag/v2.7.3) and [3.1.5](https://github.com/python/cpython/releases/tag/v3.1.5) are the latest releases.

[IPython Notebook (now called Jupyter Notebook) was released the year before (2011)](https://ipython.org/news.html#ipython-0-12).

[Many packages from Python Package Index (PyPI) only work with Python 2.x.y](https://en.wikipedia.org/wiki/History_of_Python#Compatibility).
:::

::: {.column width="50%"}
### R

Version [2.15.0](https://cran.r-project.org/src/base/R-2/) is the latest release.

[RStudio IDE was released the year before (2011)](https://posit.co/blog/rstudio-new-open-source-ide-for-r/).

dplyr (and tidyverse) has not been created, [dplyr first release was in 2014](https://dplyr.tidyverse.org//news/index.html#dplyr-011).
:::

::::

## Also in 2012 ...

Microsoft's [Windows 8 was released this year (2012)](https://en.wikipedia.org/wiki/Windows_8).

Apple's [OS X 10.8 (Mountain Lion) was released this year (2012)](https://en.wikipedia.org/wiki/MacOS).

[Git](https://en.wikipedia.org/wiki/Git) and [Mercurial](https://en.wikipedia.org/wiki/Mercurial) were the most popular version control system. [Apache Subversion](https://en.wikipedia.org/wiki/Apache_Subversion) (SVN) had lost a lot of version control system market share.

[GitHub](https://en.wikipedia.org/wiki/GitHub) replaced [SourceForge](https://en.wikipedia.org/wiki/SourceForge) as the hosting for open source software source code.

[Docker](https://en.wikipedia.org/wiki/Docker_(software)) was under development.
## In 2024 ...

::: {.notes}
This a summary of the software landscape today.
:::

:::: {.columns}

::: {.column width="50%"}
### Python

Version [3.13.0](https://github.com/python/cpython/releases/tag/v3.13.0) is the latest release.
:::

::: {.column width="50%"}
### R

Version [4.4.1](https://cran.r-project.org/src/base/R-4/) is the latest release.
:::

::::